export const ErrorCodes = {
  GUIDE_NOT_FOUND: 'GUIDE_NOT_FOUND',
  SLUG_CONFLICT: 'SLUG_CONFLICT',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  INVALID_AI_CONTENT_TYPE: 'INVALID_AI_CONTENT_TYPE',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  INVALID_RELATION: 'INVALID_RELATION',
  UNKNOWN: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = keyof typeof ErrorCodes;
